# Generated by Django 2.1.7 on 2019-03-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scannetwork', '0002_auto_20190324_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='version',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.DeleteModel(
            name='Vulnerability',
        ),
    ]
