# Generated by Django 2.1.7 on 2019-03-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scannetwork', '0004_version_vulnerability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='product_service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='version',
            new_name='version_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='product',
        ),
        migrations.RemoveField(
            model_name='version',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceversion',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scannetwork.Service', verbose_name='service_id'),
        ),
        migrations.AddField(
            model_name='serviceversion',
            name='version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scannetwork.Version', verbose_name='version_id'),
        ),
        migrations.AddField(
            model_name='product',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scannetwork.Service', verbose_name='service_id'),
        ),
    ]
