# Generated by Django 2.1.7 on 2019-03-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scannetwork', '0006_auto_20190324_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scannetwork.Service', verbose_name='service_id')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scannetwork.Version', verbose_name='version_id')),
            ],
        ),
    ]
