# Generated by Django 2.1.7 on 2019-03-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scannetwork', '0008_auto_20190325_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scannetwork.Product', verbose_name='product_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scannetwork.Service', verbose_name='service_id'),
            preserve_default=False,
        ),
    ]
