# Generated by Django 2.1.7 on 2019-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannetwork', '0009_auto_20190325_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_vulnerability',
            field=models.FloatField(default=-1, verbose_name='p_total_vulnerability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='total_vulnerability',
            field=models.FloatField(default=-1, verbose_name='v_total_vulnerability'),
            preserve_default=False,
        ),
    ]
