# Generated by Django 2.1.7 on 2019-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannetwork', '0010_auto_20190429_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='score',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_score',
            field=models.FloatField(default=-1, verbose_name='cvss_score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='risk_score',
            field=models.FloatField(default=-1, verbose_name='risk_score'),
            preserve_default=False,
        ),
    ]
