# Generated by Django 2.1.7 on 2019-05-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannetwork', '0012_remove_vulnerability_risk_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='cvss_score',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_score_v2',
            field=models.FloatField(default=0.0, verbose_name='cvss_score_v2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_score_v3',
            field=models.FloatField(default=0.0, verbose_name='cvss_score_v3'),
            preserve_default=False,
        ),
    ]
