# Generated by Django 2.1.7 on 2019-05-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannetwork', '0016_auto_20190526_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='exploitability_subscore',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='exploitability_subscore'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='impact_subscore',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='impact_subscore'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='risk_score',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='risk_score'),
        ),
    ]
