# Generated by Django 2.1.7 on 2019-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
